# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cashierdesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(200, 130, 160, 141))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.apples_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.apples_button.setObjectName("apples_button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.apples_button)
        self.apples_number = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.apples_number.setObjectName("apples_number")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.apples_number)
        self.guaves_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.guaves_button.setObjectName("guaves_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.guaves_button)
        self.guave_number = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.guave_number.setObjectName("guave_number")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.guave_number)
        self.bananas_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.bananas_button.setObjectName("bananas_button")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bananas_button)
        self.banana_number = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.banana_number.setObjectName("banana_number")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.banana_number)
        self.mangosokari_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.mangosokari_button.setObjectName("mangosokari_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.mangosokari_button)
        self.sukari_number = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.sukari_number.setObjectName("sukari_number")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sukari_number)
        self.mangoowesi_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.mangoowesi_button.setObjectName("mangoowesi_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.mangoowesi_button)
        self.owesi_number = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.owesi_number.setObjectName("owesi_number")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.owesi_number)
        self.Total = QtWidgets.QLCDNumber(self.centralwidget)
        self.Total.setGeometry(QtCore.QRect(430, 340, 64, 23))
        self.Total.setObjectName("Total")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 310, 71, 20))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.apples_button.setText(_translate("MainWindow", "apple"))
        self.guaves_button.setText(_translate("MainWindow", "guave"))
        self.bananas_button.setText(_translate("MainWindow", "banana"))
        self.mangosokari_button.setText(_translate("MainWindow", "mango(sokari)"))
        self.mangoowesi_button.setText(_translate("MainWindow", "mango(owesi)"))
        self.label.setText(_translate("MainWindow", "Total coast"))
